// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X25519Gen from "./x25519.gen";

function public_of(param) {
  return param[1];
}

function secret_of(param) {
  return param[0];
}

var KeyPair = {
  public_of: public_of,
  secret_of: secret_of
};

function load(prim) {
  return X25519Gen.load(prim);
}

function generate_keypair(prim) {
  return X25519Gen.generate_keypair();
}

function diffie_hellman(secret, $$public) {
  return X25519Gen.diffie_hellman(secret, $$public);
}

function base64_encode(prim) {
  return X25519Gen.base64_encode(prim);
}

function base64_decode(prim) {
  return X25519Gen.base64_decode(prim);
}

export {
  KeyPair ,
  load ,
  generate_keypair ,
  diffie_hellman ,
  base64_encode ,
  base64_decode ,
  
}
/* ./x25519.gen Not a pure module */
