// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var X25519Gen = require("./x25519.gen");

function load(prim) {
  return X25519Gen.load(prim);
}

function derive_public(prim, prim$1) {
  return X25519Gen.derive_public(prim, prim$1);
}

function diffie_hellman(secret, $$public) {
  return X25519Gen.diffie_hellman(secret, $$public);
}

function create(prim) {
  return X25519Gen.generate_keypair();
}

function public_of(param) {
  return param[1];
}

function secret_of(param) {
  return param[0];
}

function derive(pair, $$public) {
  return X25519Gen.diffie_hellman(secret_of(pair), $$public);
}

var KeyPair = {
  create: create,
  public_of: public_of,
  secret_of: secret_of,
  derive: derive
};

function encode(prim) {
  return X25519Gen.base64_encode(prim);
}

function decode(prim) {
  return X25519Gen.base64_decode(prim);
}

var Base64 = {
  encode: encode,
  decode: decode
};

exports.load = load;
exports.derive_public = derive_public;
exports.diffie_hellman = diffie_hellman;
exports.KeyPair = KeyPair;
exports.Base64 = Base64;
/* ./x25519.gen Not a pure module */
